/** Industry sections used by the public site (Solutions + Home). */
export type Industry = {
  id: string;
  slug: string;
  name: string;
  can: string;
  modules: string[]; // module slugs
  workflow: string[];
  inputs: string[];
  outputs: string[];
};

export const INDUSTRIES: Industry[] = [
  {
    id: "01",
    slug: "software-engineering",
    name: "Software Engineering",
    can: "Plan a system, generate a multi-file codebase, review diffs and keep the work inside a project.",
    modules: ["software-builder", "code-workspace", "ai-workforce"],
    workflow: ["Write a requirements brief", "Approve the plan", "Generate files", "Review diff", "Run tests"],
    inputs: ["Briefs", "Repositories", "Issue threads"],
    outputs: ["Codebase", "Diffs", "Test output", "Build log"],
  },
  {
    id: "02",
    slug: "legal-auditing",
    name: "Legal & Auditing",
    can: "Extract clauses, score risk, compare versions and answer questions with page citations.",
    modules: ["legal-intelligence", "document-intelligence", "assistant"],
    workflow: ["Upload agreements", "Extract clauses", "Review risk", "Compare versions", "Export report"],
    inputs: ["Contracts", "Policies", "Audit evidence"],
    outputs: ["Clause map", "Risk report", "Cited answers"],
  },
  {
    id: "03",
    slug: "academic-research",
    name: "Academic & Research",
    can: "Search sources, keep citations honest and turn lectures into notes, flashcards and quizzes.",
    modules: ["research", "academic-intelligence", "document-intelligence"],
    workflow: ["Ask a question", "Collect sources", "Draft report", "Generate study set"],
    inputs: ["Papers", "Lectures", "Datasets"],
    outputs: ["Cited report", "Notes", "Flashcards", "Quizzes"],
  },
  {
    id: "04",
    slug: "enterprise-automation",
    name: "Enterprise Automation",
    can: "Turn a single instruction into a gated, scheduled, auditable execution plan.",
    modules: ["ai-workforce", "assistant", "email-workspace"],
    workflow: ["State objective", "Review plan", "Approve steps", "Run on schedule", "Audit"],
    inputs: ["Objectives", "Policies", "Authorized integrations"],
    outputs: ["Execution plan", "Job results", "Audit trail"],
  },
  {
    id: "05",
    slug: "social-media-marketing",
    name: "Social Media Marketing",
    can: "Produce a campaign, generate captions and variants, schedule and route for approval.",
    modules: ["marketing-automation", "image-studio", "video-repurposing"],
    workflow: ["Brief campaign", "Generate content", "Pick variants", "Schedule", "Approve"],
    inputs: ["Brand kit", "Offers", "Footage"],
    outputs: ["Posts", "Captions", "Calendar", "Analytics"],
  },
  {
    id: "06",
    slug: "audio-music",
    name: "Audio & Music",
    can: "Generate narration and music with waveform review and export-ready takes.",
    modules: ["voice-studio", "music-studio", "translation-dubbing"],
    workflow: ["Write script or prompt", "Set style", "Render", "Review waveform", "Export"],
    inputs: ["Scripts", "Prompts", "Reference audio"],
    outputs: ["Narration", "Music", "Dubbed audio"],
  },
  {
    id: "07",
    slug: "visual-arts-design",
    name: "Visual Arts & Design",
    can: "Generate, vary and refine imagery from prompts and references.",
    modules: ["image-studio", "portrait-studio", "presentation-builder"],
    workflow: ["Prompt", "Generate", "Vary", "Edit", "Download"],
    inputs: ["Prompts", "References", "Aspect specs"],
    outputs: ["Images", "Variants", "Export bundles"],
  },
  {
    id: "08",
    slug: "corporate-branding",
    name: "Corporate Branding",
    can: "Hold one visual and verbal system across decks, imagery and campaigns.",
    modules: ["presentation-builder", "image-studio", "marketing-automation"],
    workflow: ["Define tokens", "Generate assets", "Review", "Publish authorized channels"],
    inputs: ["Brand tokens", "Guidelines", "Copy"],
    outputs: ["Decks", "Asset sets", "Campaign kits"],
  },
  {
    id: "09",
    slug: "architecture-real-estate",
    name: "Architecture & Real Estate",
    can: "Restage rooms, produce concept variants and package listing-ready visuals.",
    modules: ["interior-design", "image-studio", "presentation-builder"],
    workflow: ["Upload room", "Set style", "Generate concepts", "Compare", "Export"],
    inputs: ["Room photos", "Floor plans", "Style briefs"],
    outputs: ["Concepts", "Before/after", "Listing deck"],
  },
  {
    id: "10",
    slug: "sales-acquisition",
    name: "Sales & Customer Acquisition",
    can: "Qualify inbound conversations, draft replies and hand off with full context.",
    modules: ["sales-workspace", "email-workspace", "marketing-automation"],
    workflow: ["Receive lead", "Qualify", "Draft reply", "Approve", "Hand off"],
    inputs: ["Conversations", "Lead data", "Pricing"],
    outputs: ["Replies", "Qualification", "CRM activity"],
  },
  {
    id: "11",
    slug: "finance-analytics",
    name: "Finance & Analytics",
    can: "Profile spreadsheets, surface anomalies and build an explainable dashboard.",
    modules: ["finance-analytics", "document-intelligence", "presentation-builder"],
    workflow: ["Upload data", "Ask questions", "Chart trends", "Flag anomalies", "Export report"],
    inputs: ["CSV/XLSX", "Ledger exports", "Metric definitions"],
    outputs: ["Tables", "Charts", "Anomaly list", "Board report"],
  },
  {
    id: "12",
    slug: "translation-dubbing",
    name: "Translation & Dubbing",
    can: "Localise text, subtitles and spoken audio with synchronisation control.",
    modules: ["translation-dubbing", "voice-studio", "video-repurposing"],
    workflow: ["Upload", "Transcribe", "Translate", "Dub", "Sync & export"],
    inputs: ["Video", "Audio", "Documents"],
    outputs: ["Transcripts", "Subtitles", "Dubbed tracks"],
  },
  {
    id: "13",
    slug: "project-management",
    name: "Project Management",
    can: "Keep every generated asset attached to a project, a task and an owner.",
    modules: ["assistant", "ai-workforce", "document-intelligence"],
    workflow: ["Create project", "Break into tasks", "Attach assets", "Track status"],
    inputs: ["Briefs", "Deadlines", "Files"],
    outputs: ["Kanban", "Task history", "Asset register"],
  },
  {
    id: "14",
    slug: "creator-tools",
    name: "Creator & Influencer Tools",
    can: "Cut long content into shorts, suggest b-roll and localise for new audiences.",
    modules: ["video-repurposing", "broll-engine", "avatar-studio"],
    workflow: ["Upload recording", "Detect moments", "Place inserts", "Caption", "Export"],
    inputs: ["Long video", "Scripts", "Brand assets"],
    outputs: ["Shorts", "B-roll plan", "Captions"],
  },
  {
    id: "15",
    slug: "cybersecurity-logs",
    name: "Cybersecurity & Operational Logs",
    can: "Read operational logs, cluster incidents and produce a reviewable timeline.",
    modules: ["finance-analytics", "document-intelligence", "ai-workforce"],
    workflow: ["Ingest logs", "Cluster events", "Flag anomalies", "Draft incident note"],
    inputs: ["Log exports", "Alerts", "Runbooks"],
    outputs: ["Event timeline", "Anomaly report", "Incident note"],
  },
];
