/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/app'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModulesRouteImport } from './routes/modules'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ProductRouteImport } from './routes/product'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAutomationsRouteImport } from './routes/app.automations'
import { Route as AppBillingRouteImport } from './routes/app.billing'
import { Route as AppFilesRouteImport } from './routes/app.files'
import { Route as AppHistoryRouteImport } from './routes/app.history'
import { Route as AppIntegrationsRouteImport } from './routes/app.integrations'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppProjectsRouteImport } from './routes/app.projects'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppTasksRouteImport } from './routes/app.tasks'
import { Route as AppUsageRouteImport } from './routes/app.usage'
import { Route as AppModulesIndexRouteImport } from './routes/app.modules.index'
import { Route as AppModulesSlugRouteImport } from './routes/app.modules.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModulesRoute = ModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppHistoryRoute = AppHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AppRoute,
} as any)
const AppIntegrationsRoute = AppIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesIndexRoute = AppModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AppRoute,
} as any)
const AppModulesSlugRoute = AppModulesSlugRouteImport.update({
  id: '/modules/$slug',
  path: '/modules/$slug',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/files': typeof AppFilesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/usage': typeof AppUsageRoute
  '/app/': typeof AppIndexRoute
  '/app/modules/$slug': typeof AppModulesSlugRoute
  '/app/modules/': typeof AppModulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/files': typeof AppFilesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/usage': typeof AppUsageRoute
  '/app': typeof AppIndexRoute
  '/app/modules/$slug': typeof AppModulesSlugRoute
  '/app/modules': typeof AppModulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRouteWithChildren
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/modules': typeof ModulesRoute
  '/pricing': typeof PricingRoute
  '/product': typeof ProductRoute
  '/resources': typeof ResourcesRoute
  '/security': typeof SecurityRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/app/automations': typeof AppAutomationsRoute
  '/app/billing': typeof AppBillingRoute
  '/app/files': typeof AppFilesRoute
  '/app/history': typeof AppHistoryRoute
  '/app/integrations': typeof AppIntegrationsRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/projects': typeof AppProjectsRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tasks': typeof AppTasksRoute
  '/app/usage': typeof AppUsageRoute
  '/app/': typeof AppIndexRoute
  '/app/modules/$slug': typeof AppModulesSlugRoute
  '/app/modules/': typeof AppModulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/company'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/modules'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/security'
    | '/signup'
    | '/solutions'
    | '/app/automations'
    | '/app/billing'
    | '/app/files'
    | '/app/history'
    | '/app/integrations'
    | '/app/notifications'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/usage'
    | '/app/'
    | '/app/modules/$slug'
    | '/app/modules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/company'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/modules'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/security'
    | '/signup'
    | '/solutions'
    | '/app/automations'
    | '/app/billing'
    | '/app/files'
    | '/app/history'
    | '/app/integrations'
    | '/app/notifications'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/usage'
    | '/app'
    | '/app/modules/$slug'
    | '/app/modules'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/app'
    | '/company'
    | '/contact'
    | '/forgot-password'
    | '/login'
    | '/modules'
    | '/pricing'
    | '/product'
    | '/resources'
    | '/security'
    | '/signup'
    | '/solutions'
    | '/app/automations'
    | '/app/billing'
    | '/app/files'
    | '/app/history'
    | '/app/integrations'
    | '/app/notifications'
    | '/app/projects'
    | '/app/settings'
    | '/app/tasks'
    | '/app/usage'
    | '/app/'
    | '/app/modules/$slug'
    | '/app/modules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRouteWithChildren
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ModulesRoute: typeof ModulesRoute
  PricingRoute: typeof PricingRoute
  ProductRoute: typeof ProductRoute
  ResourcesRoute: typeof ResourcesRoute
  SecurityRoute: typeof SecurityRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modules': {
      id: '/modules'
      path: '/modules'
      fullPath: '/modules'
      preLoaderRoute: typeof ModulesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/automations': {
      id: '/app/automations'
      path: '/automations'
      fullPath: '/app/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/files': {
      id: '/app/files'
      path: '/files'
      fullPath: '/app/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/history': {
      id: '/app/history'
      path: '/history'
      fullPath: '/app/history'
      preLoaderRoute: typeof AppHistoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/integrations': {
      id: '/app/integrations'
      path: '/integrations'
      fullPath: '/app/integrations'
      preLoaderRoute: typeof AppIntegrationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projects': {
      id: '/app/projects'
      path: '/projects'
      fullPath: '/app/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tasks': {
      id: '/app/tasks'
      path: '/tasks'
      fullPath: '/app/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/usage': {
      id: '/app/usage'
      path: '/usage'
      fullPath: '/app/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/modules/': {
      id: '/app/modules/'
      path: '/modules'
      fullPath: '/app/modules/'
      preLoaderRoute: typeof AppModulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/modules/$slug': {
      id: '/app/modules/$slug'
      path: '/modules/$slug'
      fullPath: '/app/modules/$slug'
      preLoaderRoute: typeof AppModulesSlugRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRoute
  AppBillingRoute: typeof AppBillingRoute
  AppFilesRoute: typeof AppFilesRoute
  AppHistoryRoute: typeof AppHistoryRoute
  AppIntegrationsRoute: typeof AppIntegrationsRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppUsageRoute: typeof AppUsageRoute
  AppIndexRoute: typeof AppIndexRoute
  AppModulesSlugRoute: typeof AppModulesSlugRoute
  AppModulesIndexRoute: typeof AppModulesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRoute,
  AppBillingRoute: AppBillingRoute,
  AppFilesRoute: AppFilesRoute,
  AppHistoryRoute: AppHistoryRoute,
  AppIntegrationsRoute: AppIntegrationsRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppUsageRoute: AppUsageRoute,
  AppIndexRoute: AppIndexRoute,
  AppModulesSlugRoute: AppModulesSlugRoute,
  AppModulesIndexRoute: AppModulesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRouteWithChildren,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ModulesRoute: ModulesRoute,
  PricingRoute: PricingRoute,
  ProductRoute: ProductRoute,
  ResourcesRoute: ResourcesRoute,
  SecurityRoute: SecurityRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
